version: '3.6'
services:

  genes:
    build:
      context: ./services/genes
      dockerfile: Dockerfile-dev
    volumes:
      - './services/genes:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@variant-db:5432/variant_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@variant-db:5432/variant_test
    depends_on:
      - variant-db
      
  variant-db:
    build:
      context: ./services/genes/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres