multi_variant_data = {
    'status': 'success',
    'data'  : [
        {
            'accession'              : 'NC_012920.1',
            'alias'                  : '',
            'alt'                    : 'G',
            'assembly'               : 'GRCh37',
            'chr'                    : '1',
            'gene'                   : 'MT-CO1',
            'genomic_start'          : '6298',
            'genomic_stop'           : '6299',
            'inferred_classification': 'Variant of uncertain significance',
            'last_evaluated'         : '2017-01-04',
            'last_updated'           : '2017-09-14',
            'nucleotide_change'      : '',
            'other_mappings'         : 'NC_012920.1:m.6299A>G',
            'protein_change'         : '',
            'ref'                    : 'A',
            'region'                 : '',
            'reported_alt'           : 'G',
            'reported_classification': 'Uncertain significance',
            'reported_ref'           : 'A',
            'source'                 : 'ClinVar',
            'submitter_comment'      : 'Converted during submission to Uncertain significance.',
            'transcripts'            : 'NC_012920.1',
            'url'                    : 'https://www.ncbi.nlm.nih.gov/clinvar/RCV000431599'
        }, {
            'accession'              : 'NC_012920.1',
            'alias'                  : '',
            'alt'                    : 'G',
            'assembly'               : 'GRCh37',
            'chr'                    : '1',
            'gene'                   : 'MT-CO1',
            'genomic_start'          : '6119',
            'genomic_stop'           : '6120',
            'inferred_classification': 'Variant of uncertain significance',
            'last_evaluated'         : '2015-12-22',
            'last_updated'           : '2017-09-14',
            'nucleotide_change'      : '',
            'other_mappings'         : 'NC_012920.1:m.6120A>G',
            'protein_change'         : '',
            'ref'                    : 'A',
            'region'                 : '',
            'reported_alt'           : 'G',
            'reported_classification': 'Uncertain significance',
            'reported_ref'           : 'A',
            'source'                 : 'ClinVar',
            'submitter_comment'      : 'Converted during submission to Uncertain significance.',
            'transcripts'            : 'NC_012920.1',
            'url'                    : 'https://www.ncbi.nlm.nih.gov/clinvar/RCV000224535'
        }
    ]
}
